const GAME_WIDTH = 1280
const GAME_HEIGHT = 720
const TILE_SIZE = 160
const ANIM_FRAMERATE = 0.041
const INTERACT_DISTANCE = 256
const PLAYER_SPEED = 512  
const PLAYER_WIDTH = 96
const PLAYER_HEIGHT = 128
const PLAYER_COLLIDER_SIZE = 64
const PLAYER_COLLIDER_OFFSET = 16
const MAX_DISTANCE_RECONCILIATION = 128
const TOTAL_GAME_TIME = 360
const KILL_COOLDOWN = 30

module.exports = {
    GAME_WIDTH,
    GAME_HEIGHT,
    TILE_SIZE,
    ANIM_FRAMERATE,
    INTERACT_DISTANCE,
    PLAYER_SPEED,
    PLAYER_WIDTH,
    PLAYER_HEIGHT,
    PLAYER_COLLIDER_SIZE,
    PLAYER_COLLIDER_OFFSET,
    MAX_DISTANCE_RECONCILIATION,
    TOTAL_GAME_TIME,
    KILL_COOLDOWN,
}
